apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i03bxau2n-python
  janus-idp.io/tekton: i03bxau2n-python
  backstage.io/kubernetes-id: i03bxau2n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i03bxau2n-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
